name: Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK packages (API 35)
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      # Gradle с read-only кэшем, чтобы не падать на сохранении
      - name: Set up Gradle (read-only cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      # Раскладываем keystore из секрета
      - name: Prepare keystore
        run: |
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore/makenzi-keystore.jks

      - name: Make gradlew executable (generate if missing)
        run: |
          if [ ! -f gradlew ]; then
            ./gradlew -v || true
          fi
          chmod +x gradlew

      # Быстрая проверка наличия темы и цветов
      - name: Verify resources exist
        run: |
          ls -la app/src/main/res/values || true
          test -f app/src/main/res/values/styles.xml
          test -f app/src/main/res/values/colors.xml
          grep -q "Theme.MAKENZI.Dark" app/src/main/res/values/styles.xml

      - name: Build Release APK
        run: ./gradlew --refresh-dependencies assembleRelease --no-daemon --stacktrace --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MAKENZI-IPTV-app-release
          path: app/build/outputs/apk/release/app-release.apk
