name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags: [ 'v*', 'release-*' ]

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Кэш Gradle + wrapper
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      # Принятие лицензий без падения на "Broken pipe" и установка нужных пакетов
      - name: Install Android SDK packages
        shell: bash
        run: |
          set -eux
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"

          # Иногда latest ещё не поставлен — поставим
          if [ ! -x "$SDKMANAGER" ]; then
            "${ANDROID_SDK_ROOT}/cmdline-tools/bin/sdkmanager" --install "cmdline-tools;latest"
            SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          fi

          # Принять лицензии (НЕ используем pipefail)
          yes | "$SDKMANAGER" --licenses >/dev/null || true

          # Установить платформу и build-tools под compileSdk 35
          "$SDKMANAGER" --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"

          # Немного диагностики
          "$SDKMANAGER" --list | head -n 50 || true

      # Если ты подписываешь релиз — распакуем keystore из секретов
      # Создай в Settings → Secrets and variables → Actions:
      #   KEYSTORE_BASE64, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
      - name: Restore keystore from secrets (optional but recommended)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          set -eux
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore/makenzi-keystore.jks
          # Для AGP пути в build.gradle.kts уже должны указывать на этот файл

      # На всякий случай создадим базовые ресурсы, если их нет (чтобы не падать из-за стиля/темы)
      - name: Ensure base resources exist
        shell: bash
        run: |
          set -eux
          mkdir -p app/src/main/res/values
          if [ ! -f app/src/main/res/values/themes.xml ]; then
            cat > app/src/main/res/values/themes.xml <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.MAKENZI.Dark" parent="Theme.MaterialComponents.DayNight.NoActionBar" />
</resources>
XML
          fi

      - name: Build Release APK
        shell: bash
        run: |
          set -eux
          ./gradlew --no-daemon --stacktrace --warning-mode all clean assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Release
          path: |
            app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload AAB (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: AAB-Release
          path: |
            app/build/outputs/bundle/release/*.aab
          if-no-files-found: ignore
