name: Android Debug APK (safe)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK (API 35)
        shell: bash
        run: |
          set -euxo pipefail
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses
          "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Setup Gradle (no cache, modern action)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Make gradlew executable (if wrapper exists)
        if: hashFiles('gradlew') != ''
        run: chmod +x gradlew

      - name: Build Debug APK
        shell: bash
        run: |
          set -euxo pipefail
          if [ -f gradlew ]; then
            ./gradlew assembleDebug --no-daemon --stacktrace --warning-mode all
          else
            gradle assembleDebug --no-daemon --stacktrace --warning-mode all
          fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MAKENZI-IPTV-debug
          path: '**/outputs/apk/**/app-debug.apk'
          if-no-files-found: error
