name: Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK packages (API 35)
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      # Подкладываем keystore из секретов
      - name: Prepare keystore
        run: |
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore/makenzi-keystore.jks

      # Гарантируем наличие темы и цветов (если забыли закоммитить)
      - name: Ensure resource files (styles/colors)
        run: |
          mkdir -p app/src/main/res/values
          cat > app/src/main/res/values/styles.xml << 'EOF'
          <resources>
              <!-- Тёмная минималистичная тема для Android TV -->
              <style name="Theme.MAKENZI.Dark" parent="Theme.Material3.Dark.NoActionBar">
                  <item name="android:windowBackground">@color/black</item>
                  <item name="android:navigationBarColor">@color/black</item>
                  <item name="android:statusBarColor">@color/black</item>
              </style>
          </resources>
          EOF
          cat > app/src/main/res/values/colors.xml << 'EOF'
          <resources>
              <color name="black">#000000</color>
              <color name="white">#FFFFFF</color>
          </resources>
          EOF

      # Gradle с read-only кэшем, чтобы не падать на сохранении кэша
      - name: Set up Gradle (read-only cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Make gradlew executable (generate if missing)
        run: |
          if [ ! -f gradlew ]; then
            ./gradlew -v || true
          fi
          chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew --refresh-dependencies assembleRelease --no-daemon --stacktrace --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MAKENZI-IPTV-app-release
          path: app/build/outputs/apk/release/app-release.apk
