name: Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (API 35)
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses <<EOF
          y
          y
          y
          y
          y
          y
          y
          EOF
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # Запуск Gradle без wrapper'а: action сам подтянет Gradle 8.7 и выполнит задачу
      - name: Build debug
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug --no-daemon --stacktrace --warning-mode all
          cache-read-only: true

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MAKENZI-IPTV-debug
          path: '**/outputs/apk/**/app-debug.apk'
          if-no-files-found: error
