name: Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK packages (API 35)
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      # ⬇️ Раскладываем keystore из секрета в нужную папку
      - name: Prepare keystore
        run: |
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore/makenzi-keystore.jks

      - name: Generate Gradle Wrapper (8.7)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew --refresh-dependencies assembleRelease --no-daemon --stacktrace --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MAKENZI-IPTV-app-release
          path: app/build/outputs/apk/release/app-release.apk
